 language: node_js
 node_js: "stable"

 dist: bionic

 before_install:
    - stty cols 80

 addons:
    chrome: stable

 notifications:
  email:
    recipients:
      - shahariar.chowdhury@blinemidical.com
    on_success: always
    on_failure: always